
export const CART_DETAIL_CREATE = 'CART_DETAIL_CREATE'
export const CART_DETAIL_UPDATE = 'CART_DETAIL_UPDATE'
export const CART_DETAIL_NUM = 'CART_DETAIL_NUM'
export const CART_DETAIL_PAGE = 'CART_DETAIL_PAGE'
export const CART_DETAIL_LIST = 'CART_DETAIL_LIST'
export const CART_DETAIL_STATE_UPDATE = 'CART_DETAIL_STATE_UPDATE'
export const CART_DETAIL_USER_STATE ='CART_DETAIL_USER_STATE'


